### ISSUE TITLE
Reference links seem to be broken

### ISSUE THREAD

**Issue by sophieclayton** [efran/2015-04-09-UW#5]
When I looked at the website on my phone, the "reference" links under each section the syllabus were broken...

**Comment by efran** [comment]
I noticed this also... I did not change anything in the links. I do know where the reference pages are, however, so so.etime this weekend I could try to.fix those....

Emilia

**Comment by benmarwick** [comment]
The SWC lessons had a major reorganisation over the winter break... so our Jan workshop used the old locations of materials, and now this Spring workshop is using the new locations.... I've updated the URLs now, hopefully that's all of them!
